# Generated by Django 2.1.6 on 2019-02-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='l_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(blank=True, choices=[('M', 'Mentor'), ('S', 'Start Up')], max_length=1, null=True),
        ),
    ]
