# Generated by Django 2.1.6 on 2019-03-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
